# Generated by Django 4.1.7 on 2023-03-18 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registrar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='contraseña',
            field=models.CharField(default='DEFAULT VALUE', max_length=100),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.CharField(default='DEFAULT VALUE', max_length=100),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='usuario',
            field=models.CharField(default='DEFAULT VALUE', max_length=20),
        ),
        migrations.AlterModelTable(
            name='usuario',
            table='postres',
        ),
    ]
