# Generated by Django 4.1.7 on 2023-03-20 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registrar', '0003_usuario_created_at_usuario_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_column='title', max_length=100)),
                ('description', models.TextField(db_column='description', max_length=1000)),
                ('author', models.CharField(db_column='author', max_length=100)),
                ('year', models.IntegerField(db_column='year', default=2000)),
            ],
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
