# Generated by Django 4.1.7 on 2023-03-20 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registrar', '0004_book_delete_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(db_column='email', max_length=100)),
                ('usuario', models.CharField(db_column='usuario', max_length=10)),
                ('password', models.CharField(db_column='password', max_length=10)),
            ],
        ),
    ]
